#!/usr/bin/env bash

function _hugo_profile {
  local shome="${_hugo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  HUGO_VERSION='0.18'
}

_hugo_profile
