#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_hugo="$(hugo version 2>/dev/null | awk '{print $5}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg hugo "$ver_hugo" '{hugo: $hugo}'
}

version "$@"
